font_family      Monaco
italic_font      auto
bold_font        auto
bold_italic_font auto

font_size               14.0
adjust_line_height      6
disable_ligatures       never

enabled_layouts  stack
map kitty_mod+equal change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0

cursor_blink_interval      0.5
cursor_stop_blinking_after 10.0

scrollback_lines 7000

mouse_hide_wait 2.0

window_padding_width 2.0


foreground            #D8DEE9
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #3B4252
color8   #4C566A

# red
color1   #BF616A
color9   #BF616A

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #81A1C1
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #B48EAD

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #ECEFF4

/* foreground #e5e1d8 */
/* background #1c1c1c */

/* color0 #000000 */
/* color8 #b4b4b4 */

/* color1 #f7786d */
/* color9 #f99f92 */

/* color2  #bde97c */
/* color10 #e3f7a1 */

/* color3  #bde97c */
/* color11 #f2e9bf */

/* color4  #6ebaf8 */
/* color12 #b3d2ff */

/* color5  #fcc5e9 */
/* color13 #fae4fc */

/* color5  #e35b00 */
/* color13 #ff8a3a */

/* color6  #ef88ff */
/* color14 #e5bdff */

/* color7  #90fdf8 */
/* color15 #c2fefa */

editor vim

