set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/tpm-plugins"

set-option -g mouse on
set-option -g renumber-windows on

set-option -sg escape-time 1
bind r source-file ~/.tmux.conf \; display "Reloaded"

# Prefix
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# Spliting
bind | split-window -h 
bind - split-window -v 

# Selecting
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

set-option -g base-index 1
set-window-option -g pane-base-index 1

# Copy & Paste
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Status
set -g status-right ''

# Vim / Tmux 

run -b '~/.tmux/plugins/tpm/tpm'
